### ISSUE TITLE
logging in with unregistered email (without passkey support)

### ISSUE THREAD

**Issue by aehnh** [corbado/javascript#148]
**Describe the bug**
When logging in with unregistered email on a browser without passkey support, it redirects to email otp page instead of displaying "User does not exist" message

**To Reproduce**

1. Go to /auth on a browser without passkey support (Firefox)
2. Click on 'Login'
3. Input an unregistered email
4. Click on 'Continue'
5. Land on email otp page

**Expected behavior**
Instead of going to email otp page, "user does not exist" message should be displayed, like in passkey-supported browsers

I suspect UnknownUserError handling should be added to passkeyLoginWithFallbackFlow.ts:29

**Comment by incorbador** [comment]
@aehnh This should be fixed with our new components. I will close this, please try to reproduce it and re-open it if needed.
