### ISSUE TITLE
Registering passkey from PasskeyAppend screen on login flow

### ISSUE THREAD

**Issue by aehnh** [corbado/javascript#149]
**Describe the bug**
Registering passkey from PasskeyAppend screen on login flow doesn't properly register passkey
- same problem for PasskeyBenefit screen
- very very rarely, it works properly
- only reproducible on Mac Safari

**To Reproduce**

1. Go to '/auth' on Safari
2. Create an account without registering passkey
3. Log out
4. Log in with email otp
5. Land on PasskeyAppend screen
6. Click on 'Activate'
7. First attempt works so delete passkey and log out
8. Log in again with the same account and complete the email otp verification
9. Land on PasskeyAppend screen
10. Click on 'Activate'
11. Immediately land on LoggedIn page with no registered passkey

**Expected behavior**
Passkey input should be prompted, and upon success, the passkey should show up in the LoggedIn screen

**Comment by incorbador** [comment]
fixed with v2
