### ISSUE TITLE
Add "Secured by Corbado" badge to our components

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#165]
# Why

On the free plan our components should show a "Secured by Corbado" badge. The information for that will come from the "/projectConfig" call. We want to show this badge for:
- SignUp
- Login
- CorbadoAuth

This ticket can already be started also if the projectConfig does not yet return the setting (we will then just assume that the badge is shown for every project)

**Screenshot:**
<img width="402" alt="image" src="https://github.com/corbado/javascript/assets/134682658/0c441245-46f6-4211-813f-7e912bad69a4">

**Color logic:**
Regarding the color, we would suggest the following.
Background color: should be the same background like Primary Button Background color.
Text / Corbado logo color: should be the same like text color of primary button

**Comment by vincentdelitz** [comment]
issue updated @incorbador

**Comment by incorbador** [comment]
As @Aby-JS let's start using CSS variables
