### ISSUE TITLE
cancelling email otp challenge in Option 3: Verification at sign up (beta)

### ISSUE THREAD

**Issue by aehnh** [corbado/javascript#170]
**Describe the bug**
Clicking "Cancel" on OTP page results in "The provided one-time passcode is not valid"

**To Reproduce**

1. Set the project "Identity Verification" setting at Option 3 in dev panel
2. Initiate signup with new name and email
3. Land on Email OTP page
4. Click "Cancel"
5. See error

**Expected behavior**
Clicking cancel should go back to the signup page instead of displaying error

**Additional context**
The error was encountered on Mac Safari, but it should happen on other devices/browsers as well according to Playwright

**Comment by incorbador** [comment]
Fixed in #188 Fix cancel email OTP in verification option 3
