### ISSUE TITLE
Remove the WC from full-stack application examples

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#180]
# Why
As we don't have dedicated support for Nuxt yet, we have been using the legacy web component (WC) in our examples and blog posts so far. We now want to remove the WC completely => we must replace it in our blog posts and wizard examples for Nuxt.

This depends on #80  

# TODOS
### Next.js (@incorbador not sure what your current strategy is here, just added it for sake of completeness)
- https://github.com/corbado/example-passkeys-nextjs
- https://www.corbado.com/blog/passkeys-deployment-nextjs-heroku
- https://www.corbado.com/blog/passkeys-deployment-nextjs-vercel
- https://www.corbado.com/blog/nextjs-passkeys
- https://github.com/corbado/example-passkeys-nextjs

### Nuxt (replace with web-js)
- https://www.corbado.com/blog/passkeys-nuxtjs
- https://github.com/corbado/example-passkeys-nuxtjs

### Ruby (replace with react)
- https://www.corbado.com/blog/passkeys-ruby-on-rails-react
- https://github.com/corbado/example-passkeys-ruby-react

### SvelteKit (replace with web-js)
- https://www.corbado.com/blog/sveltekit-passkeys
- https://github.com/corbado/example-passkeys-sveltekit

# Acceptance criteria
- [x] Blog articles have been updated
- [x] GH examples are updated (on main)

**Comment by vincentdelitz** [comment]
@incorbador done

**Comment by vincentdelitz** [comment]
@lukaskratzel 
- Ruby example can be maybe de-prioritized
- with Next.js, we might need to briefly check if we even need to update the code for Vercel and Heroku, or if it can stay the same
