### ISSUE TITLE
smaller improvements in the component

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#221]
- [ ] Can we make the fingerpint icon white instead of black?:

![Image](https://github.com/corbado/corbado/assets/18458907/aa0443c8-9cfe-4412-bfdb-4b606b1a1474)

- [ ] Change the explainer text to: "You can now confirm your identity using your passkey or a one-time passcode sent to your email when you log in.”

![Image](https://github.com/corbado/corbado/assets/18458907/6e8147f3-2bc0-4cbf-bb41-6049aa1aa048)

**Comment by incorbador** [comment]
Fixed with new components
