### ISSUE TITLE
hover color of email shortcut buttons to bright

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#222]
If you hover over the Google, Yahoo or Outlook button, the hovering color is too bright / white, so that you cannot read the text anymore. Please make the hovering color a bit darker, so that the text is readable again:

![Image](https://github.com/corbado/javascript/assets/18458907/900c0502-4915-474a-b2ab-434c5254a626)

**Comment by incorbador** [comment]
Fixed with new components
