### ISSUE TITLE
SyntaxError: The requested module '/node_modules/.vite/deps/@corbado_react.js?v=fa7fa2d9' does not provide an export named 'useCorbadoSession'

### ISSUE THREAD

**Issue by barbalex** [corbado/javascript#257]
**Describe the bug**
I followed your wizard on getting user data.
Thus I added the following import:
```js
import {useCorbadoSession} from '@corbado/react';
```

**To Reproduce**
Do you have some example live code playground?
Not sure if this is the same issue but I tried to reproduce it here and that fails as well: https://codesandbox.io/p/sandbox/reactjs-playground-forked-vmzrfv?file=%2Fsrc%2Findex.js%3A4%2C1

**Expected behavior**
No error.

**Screenshots**
<img width="1710" alt="Bildschirmfoto 2024-03-29 um 19 15 05" src="https://github.com/corbado/javascript/assets/669783/a92adee0-3c18-42df-b2fc-325d10a42708">

**Additional context**
"@corbado/react": "2.0.3-alpha.0"

**Comment by barbalex** [comment]
closing this because it works with version 1.1.14. Not sure why I got the alpha version installed

**Comment by barbalex** [comment]
I just tried to update my working project from @corbado/react v1.1.14 to 2.6.0.

On the next start I get this error again:
```console
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@corbado_react.js?v=8832a8dd' does not provide an export named 'useCorbadoSession' (at Editing.tsx:6:10)
```

The line provoking the error is: https://github.com/barbalex/ps/blob/bd383c8823fb6c562d48bf81d4e76634afdc3323/src/components/Tree/Project/Editing.tsx#L6

What I tried to do:
- emptying app cache
- deleting `package-lock.json` and the `node_modules` folder, then re-installing

Reverting to v1.1.14 works. Re-updating to v2.6.0 recreates the issue.

**Comment by incorbador** [comment]
Hey @barbalex. Thanks for pointing this out. We indeed removed useCorbadoSession as we merged all its functionality with the useCorbado hook. So for you the fix is to use useCorbado in places where you used useCorbadoSession earlier. 

We will make sure to also point this our in the changelog.

**Comment by barbalex** [comment]
nice, that makes things more intuitive
