### ISSUE TITLE
Third-party cookie will be blocked

### ISSUE THREAD

**Issue by barbalex** [corbado/javascript#258]
**Describe the bug**
With corbado implemented I immediately get the following message in the devtools:
```console
Third-party cookie will be blocked. Learn more in the Issues tab.
```
<img width="823" alt="Bildschirmfoto 2024-03-30 um 18 03 55" src="https://github.com/corbado/javascript/assets/669783/85950482-526a-4afe-9b8c-4c44d9705eff">

The google page linked is: https://developers.google.com/privacy-sandbox/3pcd#report-issues

**Comment by vincentdelitz** [comment]
@barbalex thanks for reaching out.
This behavior is only possible in the development environment. If you deploy your project to production and set a CNAME (to have first-party, sameSite cookies) the warning will disappear. 

Let me know if you have more questions.
