### ISSUE TITLE
OTP input field in Firefox have the wrong size

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#274]
**Describe the bug**
The new components on firefox show the OTP input fields in the style/size. (See picture below). 
The issue can be found on the **Email OTP** and the **Phone OTP screen**. 

**To Reproduce**

1. Go to [web-js](https://feature-refactor-to-thin-frontend.web-js.playground.corbado.io/auth.html#phone-verify) or [React](https://feature-refactor-to-thin-frontend.react.playground.corbado.io/pro-3652881945085154854/signup#signup-init) example application or in the [Developer panel](https://app.corbado.com/signin#signup-init)
2. Make registration or login until the OTP screens

**Screenshots**

<img width="1289" alt="image" src="https://github.com/corbado/javascript/assets/56920624/2dc62873-48ac-4db5-9bae-fa44d28792d0">

**Comment by incorbador** [comment]
@Aby-JS can you take a look at this please?

**Comment by Aby-JS** [comment]
Sure
