### ISSUE TITLE
Build smart email inbox shortcut buttons

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#276]
# Why

Currently, if an email OTP or magic link is sent out three shortcuts for Gmail, Yahoo Mail or Outlook are displayed to the user. However, often it does not make sense to display all 3 of them, e.g. when they user has already indicated that he's using Gmail (in this case, we don't need to display Yahoo Mail). 

# TODOS

Please implement the following logic that displays the correct email shortcuts according to the [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=8969%3A3668&mode=design&t=eaKzFgNZGMBsIF6S-1) screens S1.4.1 and S1.4.2. 
Note: To see all the designs of the following cases, in Figma you can select the smart email shortcut component and in the "Mask Group" settings on the right, select the different email provider.

- Case 1: User provides an "@gmail" or "@googlemail" mail address
   - Display Gmail shortcut only
- Case 2: User provides an "@yahoo" mail address
   - Display Yahoo shortcut only
- Case 3: User provides an "@outlook" or "@hotmail" mail address
   - Display Outlook shortcut only
- Case 4: User provides an "@icloud" mail address
   - Display iCloud mail shortcut only
- Case 5: User provides any other mail address (e.g. protonmail, AOL, GMX, Zoho)
   - Display no shortcut

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] Depending on 5 test mail addresses, the right behavior should be displayed. These test email addresses are e.g.:
   - vincdelitz@googlemail.com
   - vincdelitz@yahoo.de
   - vincent.delitz@hotmail.com
   - vincent.delitz@icloud.com
   - vincdelitz@aol.com

**Comment by Adam3371** [comment]
Tested:
Email provider filtering works.
Component size when not showing any shortcut should be the size of the phone OTP screen.
Update link for single outlook button
