### ISSUE TITLE
Feedback socials (not done completely yet)

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#300]
- [ ] cancelling the login flow with Microsoft leads to this ugly error message on top:
<img width="463" alt="image" src="https://github.com/corbado/javascript/assets/18458907/9b8635b0-68be-44ad-a5a8-493ae0e6f152">

**Comment by Adam3371** [comment]
Update
- [ ] If a social login is aborted by the user, change the error message to: "You did not grant access to your \<social service\> Account."
- [ ] <social service> should be replaced by the Social provider the user selected.

**Comment by Aby-JS** [comment]
@incorbador this is not possible for now, as right now our error code is `unknown`. If this is fine then I will change text for unknown error for social provider specific error but this can cause confusion on the BE side in the future as it can be used by other developers for showing other unknows errors.
Let me know what you think.

**Comment by Adam3371** [comment]
2 Tickets have been created to close this:

[FE ticket](https://github.com/corbado/javascript/issues/378)
[BE ticket](https://github.com/corbado/corbado/issues/3349)
