### ISSUE TITLE
What changed between @corbado/react 1.1.14 and 2.5.4?

### ISSUE THREAD

**Issue by barbalex** [corbado/javascript#304]
I would like to know whether to upgrade and how

**Comment by incorbador** [comment]
Hey @barbalex. In the upcoming days we will publish a changelog for @corbado/web-js and @corbado/react.

You can upgrade any time. If you decide to do so an update of you package.json is enough.
We suggest doing this on your testing environment first and keeping an eye on the (few) breaking changes:
- the structure of custom translations has changed (only relevant for you if you make use of custom translations)
- css classes have been changed which breaks style customizations => if you are making use of those you have to re-apply them in the v2 component (support is still there, just the classes have changed)

New features in v2 (non-breaking):
- overall style of the component has changed => to get an impression about how the v2 component looks, either check out our docs or go to https://app.corbado.com where we use the component
- support for additional login identifiers has been added: v2 components support emails, phone numbers and unique usernames while v1 only supported emails => you can enable them 
- support for social logins will soon be added (its in private beta right now and will be published next week)

**Comment by incorbador** [comment]
I'll close this for now. If there are any other questions, just reopen the ticket :)
