### ISSUE TITLE
Improve Frontend Integration docs.

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#319]
**Describe the bug**
We need to improve the https://docs.corbado.com/frontend-integration/ui-components for better understanding of new changes.

**Expected behavior**
- We need to remove the Signup and Login components as they have been deprecated and now we support direct navigation to login and signup states with `#login-init` and `#signup-init` urls.
- We should change the custom theming section at https://docs.corbado.com/frontend-integration/ui-components/customization#2-3-creating-a-custom-theme as those CSS classes are now depreciated.

**Comment by incorbador** [comment]
Additional points:
- document the setting about navigation

**Comment by incorbador** [comment]
Our docs are maintained in this repo: https://github.com/corbadotech/docs
There is a README that described the local setup.
Just put changes on a new branch and create a PR :)
