### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by lukaskratzel** [corbado/javascript#328]
**Describe the bug**
When integrating either @corbado/web-js or @corbado/react into frontend frameworks, bundle size tends to get very large.

**To Reproduce**

1. React: Taken from our developer panel preview ui, which is a react application with only @corbado/react as added dependencies. The resulting total javascript bundle is 1.13mb large (310kb compressed).
2. Next.js: Taken from our [external page](https://www.corbado.com/), including vs. excluding the @corbado/react package from the landing page makes around a 300kb difference in first load compressed javascript size.
3. Angular: Using @corbado/web-js makes the bundle size increase by around 1mb (300kb compressed), which can be seen when building our [angular example](https://github.com/corbado/example-passkeys-angular/tree/migrate-to-web-js).

So it's around 300kb of compressed javascript that's added to the bundle size when integrating Corbado.

**Comment by Aby-JS** [comment]
There are three major reductions in our package code base that we can make:

1. Remove auto-generated code from the `web-core` package and write our custom code.
2. Remove SVG assets from `shared-ui` package and serve them from a different source
3. Our minified CSS is also part of our JS bundle which has a size of 25KB. Storing it in our CDN/server will be beneficial.

The estimated improved bundle size is:
- ~800KB uncompressed (~500KB reduction from auto-generated code, ~50KB from SVGs and ~25KB from CSS)
- ~200KB compressed (based on the fact that compressed size is approximately 25% of the complete size)

**Comment by incorbador** [comment]
@Aby-JS Please document all your findings here (including how you calculated the numbers).

**Comment by Aby-JS** [comment]
Here is the approach for finding the impact of three above mentioned factors:

1. To find the impact of openapi auto-generated code in the `web-core` package I used webpack to build only that part of the code and then checked the resultant JS size.
2. The impact of SVGs can be easily found by checking size of the folder as the files are directly converted to React SVGs.
3. The impact of bundled CSS was found using `esbuild`
