### ISSUE TITLE
Research: How could support for server side rendering look like 

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#346]
# Why
When we started to build @corbado/react we did not include server side rendering. Our react package can be used with NextJS but the experience is not great. We even experience this ourself (go to corbado.com and see how the components load).

In this ticket we want to list options how we can introduce support for @corbado/react.

Questions that should be addressed:
- do we need to build a separate npm package?
- what are the changes we need to make in the react, web-core and shared-ui packages?
- how could a minimal solution look like that just makes sure that the initial screen of the component is server side rendered?
- how could this minimal solution be extended?

Document all findings as part of this ticket.

**Comment by Aby-JS** [comment]
## Implementation Details
Now, that we have gone through the challenges and their solutions used by Clerk we can discuss the types of features we should provide from our `nextjs` package to better support SSR.

### 1. Do we need to build a separate npm package?
Yes. Though we can also provide our custom SSR components by adding a path in our current package like `@corbado/react/server` it would be better if we create a separate package. 
Creating a separate package would keep our react package light and we would not need to include the server side components, helpers and middleware into that package.

### 2. What are the changes we need to make in the react, web-core and shared-ui packages?
To discuss the changes we need to first discuss the features we want to provide. Based on our current target (to improve initial load) here are my suggestions.
1. Utilize `next/router` for routing management in our NextJS package. This could be achieved by adding support for custom route handler in SharedUI package's `ProcessHistoryHandler` service.
2. Create a wrapper for `CorbadoProvider` similar to how Clerk does for their global context to support for hybrid component rendering.
3. Create a `CorbadoAuth` component in `NextJS` package which would perform most of the operations inside `shared-ui` package's `ProcessHandler.init` on the server side and the provider that data to `react` package's `FlowHandlerProvider` to then maintain the auth flow on the client side. This would achieve the initial server side render and would also keep the changes to minimal.
4. Provide a `corbadoMiddlerware` which will use cookies sent from the client side. The implementation details of this can be used from the `NextJS` demo of the Corbado component. The inspiration of this comes from the [Clerk's middleware](https://clerk.com/docs/references/nextjs/clerk-middleware)
5. Prover helper utilities like `cobadoAuth` for server side components similar to `useCorbado` hook on client side components which could provider more context about the authenticated state and the authenticated user to server side components. The inspiration of this comes from Clerks' [`auth()`](https://clerk.com/docs/references/nextjs/auth) method and [`currentUser()`](https://clerk.com/docs/references/nextjs/current-user) method.

### 3. how could a minimal solution look like that just makes sure that the initial screen of the component is server side rendered?
The deatils for solution for this can be found in point `2.3` above. The jist of it is that we can create a `CorbadoAuth` component in `NextJS` package

### 4. how could this minimal solution be extended?
Based on what we implement from the point 2 above we can then move the remaining functionalities for the extended solution. After implementing solutions suggested in point 2 we would be supporting all the necessary functionalities and the only remaining extensions would be that we can also provide a server side rendered `PasskeyList` component.

**Comment by incorbador** [comment]
@Aby-JS I have move this to our internal docs.
