### ISSUE TITLE
Improve mobile view on Android

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#363]
During testing the new components at passkeys.eu with my Samsung Galaxy S21, I found some UI/UX bugs that should be fixed.

- [x] Can we try to keep the explainer texts in two lines if possible?
![Screenshot_20240516_064556_Chrome.jpg](https://github.com/corbado/javascript/assets/18458907/e050df00-df32-4fed-aafc-fa368dcd89d4)

- [x] "PASSKEYS" centered looks a bit odd. It should have the same style like other headings/larger fonts of the components. Maybe also left align it?
- [x] Moreover, the "X" for a passkey list element is not centered (see also the different margins on top and bottom
![Screenshot_20240516_064623_Chrome.jpg](https://github.com/corbado/javascript/assets/18458907/6e4f7839-2d7d-4417-bef3-c208a51942b3)

- [x] The Passkey Icon on the left is way too small. Moreover, can we keep the text below "Log in" in one line

![Screenshot_20240516_064651_Chrome.jpg](https://github.com/corbado/javascript/assets/18458907/d9d79e27-f149-471e-9510-3415bd3d85c5)

- [x] Logout should automatically lead to the login page instead of the signup page

**Comment by lukaskratzel** [comment]
@Adam3371 Some remarks for how we can improve the DX of component integration:
- Our default component is very opinionated in styling, so we should enforce these opinions no matter what the sorrounding page context contains regarding styles. An example of this is text alignment. Our component should keep a text alignment of left even though the surrounding context might have a different text alignment. The user should only change this behaviour by customizing component classes directly, not the surrounding context.
- The component currently overflows on screen sizes / containers smaller than 400px as this value is hardcoded. Many phones have < 400px of screen size, so our default behaviour should constrain to these limits.
- We set hard limits for example for the .cb-pk-append-points-section and .cb-last-identifier classes of 83% width. When the component shrinks to adapt to smaller screen sizes, we loose too much available space by 'wasting' these 17% of potential space and this doesn't include the padding the components container has.

**Comment by Adam3371** [comment]
@lukaskratzel  Thank you very much!
@incorbador  => What do you think about this points? What are the priorities for this points?
