### ISSUE TITLE
Setting the initialBlock property of CorbadoAuth React component has no effect

### ISSUE THREAD

**Issue by icflorescu** [corbado/javascript#453]
In a Next.js application, setting the `initialBlock` property on a `<CorbadoAuth />` component has no effect:

```ts
<CorbadoAuth
  initialBlock="login-init" // 👈 setting this has no effect
  onLoggedIn={async () => {
    // do stuff...
  }}
/>
```

The components **always defaults to rendering the sign-up form**, regardless of the above.

I had a quick glance at the source code and I'm suspecting this happens because you're not passing the provided property down to the underlying `FlowHandlerProvider` here:

https://github.com/corbado/javascript/blob/develop/packages/react/src/screens/core/CorbadoAuth.tsx#L10-L15

```ts
import type { CorbadoAuthConfig } from '@corbado/types';
import type { FC } from 'react';
import React from 'react';

import { AuthFlow } from '../../components';
import FlowHandlerProvider from '../../contexts/FlowHandlerProvider';

const CorbadoAuth: FC<CorbadoAuthConfig> = ({ onLoggedIn, handleNavigationEvents }) => {
  return (
    <FlowHandlerProvider
      onLoggedIn={onLoggedIn}
      handleNavigationEvents={handleNavigationEvents}
    >
      <AuthFlow />
    </FlowHandlerProvider>
  );
};

export default CorbadoAuth;
```

**Comment by incorbador** [comment]
Hey @icflorescu, thanks for the ticket and your support 👍 

The code snippet you provided indeed pointed to the right part and has been fixed :)
